"""add workspace_path and analysis to projects

Revision ID: f4e264dea9bd
Revises: 075be60f835b
Create Date: 2026-08-27 08:12:03.529862

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f4e264dea9bd'
down_revision: Union[str, Sequence[str], None] = '075be60f835b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('workspace_path', sa.String(), nullable=True))
    op.add_column('projects', sa.Column('analysis', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('projects', 'analysis')
    op.drop_column('projects', 'workspace_path')
    # ### end Alembic commands ###
